### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SeolJaeHyeok** [wanted-pre-onboarding-4/Fruitte#14]
- [x] '/' -> '/fruitstore' 리다이렉션 - 재혁
- [ ] 주문 완료 페이지 데이터 넘겨 받아 화면 그리기 - 후경
- [x] /admin/register 페이지 조립 - 보선
- [x] /admin/management 페이지네이션 적용 - 명원
- [x] /fruitstore 아이콘 토글 - 주완
- [x] 유의미한 데이터로 변경 - 우리 모두
- [x] Footer Component 제작 - 재혁
- [x] admin 라우팅 처리 - 재혁
- [ ] 배포 - 명원
- [x] README 작성 - 재혁
